# Copyright Contributors to the KubeOpenCode project
# Agent configuration for AI agent with credentials
apiVersion: kubeopencode.io/v1alpha1
kind: Agent
metadata:
  name: fast
spec:
  agentImage: quay.io/kubeopencode/kubeopencode-agent-opencode:latest
  executorImage: quay.io/kubeopencode/kubeopencode-agent-devbox:latest
  workspaceDir: /workspace
  serviceAccountName: acm-agent
  maxConcurrentTasks: 2
  config: |
    {
      "$schema": "https://opencode.ai/config.json",
      "model": "google/gemini-3-fast-preview",
      "small_model": "google/gemini-3-fast-preview",
      "share": "disabled",
      "autoupdate": false
    }
  contexts:
    - name: basic-rules
      type: Text
      text: |
        ## Agent Behavior Rules
        1. Always sign-off commits with `--signoff` flag.
  credentials:
    # Mount entire secret - all keys become env vars automatically
    - name: git
      secretRef:
        name: git-settings
    - name: gemini
      secretRef:
        name: gemini-credentials
    # GitHub App credentials mounted as directory
    # The devbox image has built-in scripts that automatically use these
    # for transparent gh CLI and git authentication
    - name: github-app
      secretRef:
        name: github-bot-credentials
    - name: slack
      secretRef:
        name: slack-webhook-url