# Copyright Contributors to the KubeOpenCode project
# TaskTemplate for konflux common pipeline migration tasks (batch mode)
apiVersion: kubeopencode.io/v1alpha1
kind: TaskTemplate
metadata:
  name: konflux-common-pipeline-migration-task-template
spec:
  # Reference the agent that will execute tasks created from this template
  agentRef:
    name: fast
  # Contexts that will be merged with task-specific contexts
  contexts:
    - name: bot-instructions
      type: Text
      text: |
        ## Agent Overview
        You are an agent that handles **batch** pipeline migration tasks for the konflux-build-catalog repository (https://github.com/stolostron/konflux-build-catalog).

        **Important:** The konflux-build-catalog repository is already mounted at `./konflux-build-catalog` via Git context. Do NOT run `git clone` - just use the files directly from that path.

        ## Batch Processing Workflow

        ### Step 1: Collect All Migration Issues
        First, list all open issues with the `migration` label:
        ```bash
        gh issue list --repo stolostron/konflux-build-catalog --label migration --state open --json number,title,url,body
        ```

        If no issues are found, send a Slack notification and exit:
        ```bash
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"No open migration issues found. Nothing to process."}' \
          "$SLACK_WEBHOOK_URL"
        ```

        ### Step 2: Parse and Group Issues
        Each issue body contains a JSON block with migration details. Extract and parse this JSON:
        ```json
        {
          "depName": "quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta",
          "currentValue": "0.7",
          "newValue": "0.8",
          "currentDigest": "sha256:...",
          "newDigest": "sha256:...",
          "packageFile": "pipelines/common-oci-ta.yaml"
        }
        ```

        Group all migrations by `packageFile` to minimize the number of file edits.

        ### Step 3: Check MIGRATION.md (Optional but Recommended)
        For each task bundle, you may check if there are breaking changes:
        ```
        https://raw.githubusercontent.com/konflux-ci/build-definitions/main/task/<task-name>/<new-version>/MIGRATION.md
        ```

        Extract `<task-name>` from `depName` (e.g., `task-buildah-oci-ta` from `quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta`).

        - If MIGRATION.md says "no action needed" → proceed with update
        - If MIGRATION.md has breaking changes → skip this issue, add to skipped list

        ### Step 4: Create One PR Per Pipeline File
        Due to CI requirements, each pipeline file MUST have its own separate PR.

        For each `packageFile` group (from Step 2), perform these operations:

        ```bash
        # 1. Create a dedicated branch from main
        cd ./konflux-build-catalog
        git checkout main
        git pull origin main
        BRANCH_NAME="chore/migrate-$(basename $PACKAGE_FILE .yaml)-$(date +%Y%m%d%H%M)"
        git checkout -b "$BRANCH_NAME"

        # 2. Update bundle references in the file
        # For each migration in this file group:
        #   - Find the bundle reference matching `depName`
        #   - Update version tag AND digest:
        #     Old: <depName>:<currentValue>@<currentDigest>
        #     New: <depName>:<newValue>@<newDigest>
        #   - Use the exact `newDigest` value from the issue JSON

        # 3. Commit and push
        git add "$PACKAGE_FILE"
        git commit -s -m "chore: migrate tekton bundles in $(basename $PACKAGE_FILE)"
        git push origin "$BRANCH_NAME"

        # 4. Create PR
        gh pr create --repo stolostron/konflux-build-catalog \
          --title "chore: migrate tekton bundles in $(basename $PACKAGE_FILE)" \
          --body "$(cat <<EOF
        ## Summary
        Automated migration of Tekton task bundles in \`$PACKAGE_FILE\`.

        ## Issues Addressed
        - Fixes #<issue1>
        - Fixes #<issue2>
        ...

        ## Changes
        | Task | Version |
        |------|---------|
        | <task1> | <currentValue1> → <newValue1> |
        | <task2> | <currentValue2> → <newValue2> |
        ...

        EOF
        )"

        # 5. Return to main for next file
        git checkout main
        ```

        **Important:**
        - Create a separate branch and PR for EACH pipeline file
        - Use "Fixes #xxx" syntax to automatically close issues when PR is merged
        - Issues affecting the same file should be grouped into one PR for that file
        - Track all created PR URLs for the Slack notification

        ### Step 5: Send Slack Notification

        **Success (all PRs created):**
        ```bash
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"<@U01TX25RJ3B> Batch migration completed!\n\nPRs created: '"$PR_COUNT"'\n'"$PR_LIST"'\n\nIssues addressed: '"$ISSUE_COUNT"'"}' \
          "$SLACK_WEBHOOK_URL"
        ```

        Where `$PR_LIST` is a newline-separated list of PR URLs, e.g.:
        ```
        - common-oci-ta.yaml: https://github.com/stolostron/konflux-build-catalog/pull/123
        - common-fbc.yaml: https://github.com/stolostron/konflux-build-catalog/pull/124
        ```

        **Partial success (some issues skipped):**
        ```bash
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"<@U01TX25RJ3B> Batch migration completed with some issues skipped.\n\nPRs created: '"$PR_COUNT"'\n'"$PR_LIST"'\n\nProcessed: '"$SUCCESS_COUNT"' issues\nSkipped (breaking changes): '"$SKIPPED_ISSUES"'\n\nPlease handle skipped issues manually."}' \
          "$SLACK_WEBHOOK_URL"
        ```

        **No processable issues:**
        ```bash
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"<@U01TX25RJ3B> Batch migration: All issues have breaking changes and were skipped.\n\nSkipped issues: '"$SKIPPED_ISSUES"'\n\nPlease handle manually."}' \
          "$SLACK_WEBHOOK_URL"
        ```

        ## Important Rules
        1. Create ONE PR per pipeline file (not one PR for all changes)
        2. Group issues by `packageFile` - all issues for the same file go into one PR
        3. Use the exact `newDigest` value from each issue's JSON - do not compute or fetch digests
        4. If an issue has breaking changes in MIGRATION.md, skip it and add to the skipped list
        5. Always use "Fixes #xxx" in PR body to auto-close issues
        6. If no issues can be processed, do NOT create any PRs
    - name: konflux-build-catalog
      type: Git
      git:
        repository: https://github.com/stolostron/konflux-build-catalog.git
        ref: main
      mountPath: konflux-build-catalog
