apiVersion: kubeopencode.io/v1alpha1
kind: Task
metadata:
  generateName: konflux-common-pipeline-migration-task-
  namespace: acm
spec:
  taskTemplateRef:
    name: konflux-common-pipeline-migration-task-template
  description: |
    Process all open migration issues in batch mode for the konflux-build-catalog repository.
